### PR TITLE
Prevent reading off the end of the buffer if transformation arguments are (validly) omitted

### PR DESCRIPTION
**Pull request by cysp**
The `translate` and `scale` transformations have optional arguments ([MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform)), but if they are omitted then the parser blindly reads past the end of its`transformOperands` vector.

This change actually provides default (safe) values for mandatory arguments for the `translate` and `scale` operations as well, since that's probably better than reading _something_ out of an empty vector? I haven't touched the other operations though, so they're inconsistent in that regard. Would it be better to undo the part of this change that allows for the first operands to be omitted? e.g. by applying this diff:
```diff
--- i/SVGEngine.mm
+++ w/SVGEngine.mm
@@ -332,16 +332,13 @@ @interface SVGAttributeSet () {
                                                                     0, 0);
                     }
                 } else if([transformCmd isEqualToString:@"translate"]) {
-                    float tx = 0, ty = 0;
-                    if (transformOperands.size() > 0)
-                        tx = transformOperands[0];
+                    float tx = transformOperands[0];
+                    float ty = 0;
                     if (transformOperands.size() > 1)
                         ty = transformOperands[1];
                     additionalTransform = CGAffineTransformMakeTranslation(tx, ty);
                 } else if([transformCmd isEqualToString:@"scale"]) {
-                    float sx = 1;
-                    if (transformOperands.size() > 0)
-                        sx = transformOperands[0];
+                    float sx = transformOperands[0];
                     float sy = sx;
                     if (transformOperands.size() > 1)
                         sy = transformOperands[1];
```

### CODE REVIEW

**Comment by fjolnir** [comment]
Wouldn't hurt to add a minimum count guard to the `if`s for the other commands. Like: ` else if([transformCmd isEqualToString:@"skewY"] && transformOperands.size() >= 1)`

**Comment by cysp** [comment]
Whitespace-ignoring view of the top commit:
https://github.com/pocketsvg/PocketSVG/pull/122/commits/b713c00aa37ae16a35c02d4c1149c9636c7962bd?w=1

**Comment by cysp** [comment]
Whitespace-ignoring view of the top commit:
https://github.com/pocketsvg/PocketSVG/pull/122/commits/0fd0162c702b0ffc3b2dec1a6f65763e4dbbde42?w=1

**Comment by arielelkin** [comment]
Looking good. 

Just a quick headsup: we now have a [CHANGELOG](https://github.com/pocketsvg/PocketSVG/blob/master/CHANGELOG.md) to make it easier to keep track of new features and bugs, and to credit our contributors. It'd be great if your PR also updates it.

**Comment by fjolnir** [comment]
Sorry to reply after you wrote the change, but I think the added readability of not having nested ifs, is worth the minor performance hit while reading corrupt SVGs.

**Comment by cysp** [comment]
My thinking with nesting the conditionals was less about performance and more because then each branch of the chained-ifs deals with one transformation operation, whether it's validly specified or not.
I can see an argument for having each branch deal with only valid operations though, as then a final `else` could be added to catch both unknown and invalid operations.

**Comment by arielelkin** [comment]
merged via https://github.com/pocketsvg/PocketSVG/commit/c441d25b255c8786fee287540a64d7925f2d7dc5

**Pull request closed without merging**
