### PR TITLE
support for viewBox attribute

### PR DESCRIPTION
**Pull request by arielelkin**
Based on @NeedNap's work on https://github.com/pocketsvg/PocketSVG/pull/181

### CODE REVIEW

**Review by NeedNap — APPROVED** [review]
I think it's a good solution. I'll give it a try as soon as I can

**Comment by NeedNap** [comment]
You should check this function at line https://github.com/pocketsvg/PocketSVG/blob/059f892db4dbfb59f6ce3e512fd164848999fe64/Sources/SVGBezierPath.mm#L209 because not all code paths return a value.
You can see it in the "checks" console

**Comment by arielelkin** [comment]
@NeedNap thanks, that's fixed now.

**Comment by arielelkin** [comment]
@NeedNap did you have a chance to give this a try?

**Comment by arielelkin** [comment]
Hello @NeedNap! Could I please get your approval before merging this? I want to make sure it works for you as you requested the original feature.

**Comment by NeedNap** [comment]
Hi @arielelkin, I think it's ok. You can merge it.

**Comment by arielelkin** [comment]
This is now in 2.7.0 🎉

**Comment by NeedNap** [comment]
Thank you

**Comment by robaho** [comment]
Hi @arielelkin Is there any docs on how to use this? I have the following SVG that fails to display.

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="29.714954376220703 -210 180.5701141357422 180" fill="#e8eaed" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" transform="matrix(-1.8369701987210297e-16,-1,-1,1.8369701987210297e-16,0,0)"><path d="M50-30q-12.75 0-18.125-11.375T34.5-62.5L90-130v-60H80q-4.25 0-7.125-2.875T70-200t2.875-7.125T80-210h80q4.25 0 7.125 2.875T170-200t-2.875 7.125T160-190h-10v60l55.5 67.5q8 9.75 2.625 21.125T190-30zm0-20h140l-60-73v-67h-20v67zm70-70"></path></svg>
```

The only way I can get it to work is by changing SVGLayer.m with

```obj-c
        CGRect const pathBounds = path.bounds;
        layer.frame = CGRectApplyAffineTransform(pathBounds, layerTransform);

        CGAffineTransform tx = CGAffineTransformIdentity;
        if(!CGRectEqualToRect(self.viewBox,CGRectNull)) {
            tx = CGAffineTransformTranslate(tx,self.viewBox.origin.x,self.viewBox.origin.y * -1);
        }

        CGAffineTransform const pathTransform = CGAffineTransformConcat(tx,
                                                    CGAffineTransformConcat(CGAffineTransformMakeTranslation(-pathBounds.origin.x,-pathBounds.origin.y),scale));
```


I can't seem to get it to display in any of the upper layers (e.g. demo apps) with any sort of transform related to the view box.

The SVG displays fine in browser and other online viewers.

**Pull request merged**
