### PR TITLE
Added support for the "transform" attribute in basic tags.

### PR DESCRIPTION
**Pull request by adario**
The "transform" attribute is now parsed for the rect, circle, ellipse and line tags.

Similar support should be added to the path and polygon tags.

### CODE REVIEW

**Comment by arielelkin** [comment]
Thanks Dario. 

LGTM

@fjolnir , any thoughts?

**Comment by adario** [comment]
@arielelkin @fjolnir should you accept the changes, it'd be nice to refactor the top-level transform tag parsing to use the method in the patch (obviously derived from the original).

A sample SVG to test is available at https://www.flaticon.com/free-icon/missile_1537245 — if I remember correctly, this contains a transform attribute with a matrix component in a rect tag.

**Comment by arielelkin** [comment]
@adario thanks again for the PR, and apologies for the delay in following up. 

https://github.com/pocketsvg/PocketSVG/blob/master/SVGLayer.m#L78

**Comment by arielelkin** [comment]
@adario thanks again for the PR, and apologies for the delay in following up. 

The codebase currently supports the `transform` attribute for basic tags: https://github.com/pocketsvg/PocketSVG/blob/master/SVGLayer.m#L78

In fact, the sample SVG you provided (missile.svg) renders correctly in the current state of the codebase. I'm attaching [here](https://github.com/pocketsvg/PocketSVG/files/4193009/missile_modified.svg.zip)
a slightly modified version of it where I've modified the transform of one of the rectangles, and you can see that it's being rendered as expected. 

So can you please help me fully understand the purpose of your PR?

**Comment by adario** [comment]
@arielelkin thanks for pointing this out — if I'm not mistaken, that applies to SVGLayer objects.  The patch I submitted was about the `transform` attribute in SVGBezierPath objects: I'm not using SVGLayer at all.

**Comment by arielelkin** [comment]
Ah, I understand now. 

By design, the transform isn't reflected in what's returned by SVGBezierPath, because we assume the client using SVGBezierPath is interested purely in the abstract paths as `CGPaths`, to then eventually apply his own `CGAffineTransforms`. 

I'd be open to changing this default behaviour so that transforms aren't ignored, but I wouldn't want to duplicate what's already exists in `SVGEngine`:
https://github.com/pocketsvg/PocketSVG/blob/master/SVGEngine.mm#L326

Would you be happy modifying your PR so that SVGBezierPath uses `readAttributes` instead? Perhaps you could also improve `readAttributes` with your changes, if needed.

**Comment by adario** [comment]
@arielelkin sure, I'll see if I can modify my changes in order to use `readAttributes` (if possible) — not sure when I'll have time to do so, though.

**Comment by fjolnir** [comment]
We can't change the default behavior, everything assumes the current one. But it's trivial to apply the transform to the parsed path: `[mySVGBezierPath applyTransform:[mySVGBezierPath. svgAttributes[@"transform"] CGAffineTransformValue]]`

**Comment by adario** [comment]
Unfortunately in the case when a .svg contains several paths, with differing transforms, it is not so trivial.

**Comment by fjolnir** [comment]
Can't just loop over them?
`for (path in svgPaths) { [path applyTransform:[path. svgAttributes[@"transform"] CGAffineTransformValue]]; }`

**Comment by adario** [comment]
Doesn’t work as expected – I’m not using SVGLayer, just the paths.

**Comment by fjolnir** [comment]
Alright

**Pull request closed without merging**
